pipeline {
    agent any
    stages {
        stage('CleanWorkspace') {
            
            steps {
                deleteDir()
            }
            
        }
        
        stage('Experiment') {
            steps {
                script{
                    sh 'java -version'
                }
            }
        }
    }
}
