pipeline {
    agent any
    stages {
        stage('CleanWorkspace') {
            
            steps {
                deleteDir()
            }
            
        }
        stage('Clone') {
            environment {
                TRIMMED_BRANCH = sh(script:'echo ${GIT_BRANCH##origin/}', returnStdout: true).trim()
            }
            steps {
                git branch: "${env.TRIMMED_BRANCH}", url: "${GIT_URL}"
                sh 'mkdir deployment/env-utils-image/build'   
            }
        }
        stage('Experiment') {
            steps {
                script{
                    sh 'java -version'
                }
            }
        }
    }
}
